#!/bin/bash

OLD_PWD=$(pwd)
WORKDIR=$(dirname $0)
cd $WORKDIR

function check_version() {
    package=$1
    last_archive=$(ls -1 downloads/${package}_*.orig.* | tail -1 2>/dev/null)
    version=${last_archive#downloads/${package}_}
    version=${version%.orig.*}
    if [ "X${version}" == "X" ];
    then
        version=0
    fi
    current_version=${version}
}

for package in $(ls -1 watch);
do
    echo ${package}
    check_version ${package}
    uscan --download --package ${package} \
          --upstream-version ${current_version} \
          --watchfile watch/${package} \
          --destdir ./downloads/
done

cd $PWD
# Exit 0 is needed here to avoid using last uscan exit code.
:
