#!/bin/bash

OLD_PWD=$(pwd)
WORKDIR=$(dirname $0)
cd $WORKDIR

function check_version() {
    package=$1
    last_archive=$(ls -1 downloads/${package}_*.orig.* 2>/dev/null | tail -1 2>/dev/null)
    version=${last_archive#downloads/${package}_}
    version=${version%.orig.*}
    if [ "X${version}" == "X" ];
    then
        version=0
    fi
    current_version=${version}
}

function check_upstream() {
    echo ${1}
    check_version ${1}
    uscan --download --package=${1}\
          --upstream-version=${current_version} \
          --watchfile=watch/${1} \
          --no-symlink --destdir=./downloads/ 2>/dev/null
}

if [ $# -gt 0 ];
then
    check_upstream ${1}
else
    for package in $(ls -1 watch);
    do
        check_upstream ${package}
    done
fi
cd $PWD
# Exit 0 is needed here to avoid using last uscan exit code.
:
